### ISSUE TITLE
What are some "Best Practices" for implementing DevOps? List and give a brief description of 3. (refer to https://www.atlassian.com/devops/what-is-devops/devops-best-practices)

### ISSUE THREAD

**Issue by sallyom** [sallyom/ds219sp2022#58]
@gian-s
@jicheolha
@AngeloFacciponti-Mennella

**Comment by gian-s** [comment]
**Observability** is one of the best practices in dev ops . The three aspects of **Observability** are **Logs/Traces/Metrics**
Gathering **logs** of a system's performance. **Traces** track the flow of logic within a system. **Metrics** include CPU/ram reservation/usage/disk space/ and network connectivity/
